### ISSUE TITLE
Have individual items, runes, summoner spells as direct champion attribute

### ISSUE THREAD

**Issue by PaulQbFeng** [PaulQbFeng/too-tanky#86]
On top of having the items stored in `champion.items`, have them referenced as direct attribute
to enable this type of behaviour: 

`champion.luden_echo.damage`
instead of 
`champion.get_item("Luden's Echo").damage`

has to be done after `InventoryMixin` is created

**Comment by PaulQbFeng** [comment]
Opinion @Lysxia @LinSun00 ?

**Comment by Lysxia** [comment]
I find it harder to read because you have to recognize the attribute as an item to understand that it's handled specially, and you have to mangle non-alphabetic characters in names.

**Comment by PaulQbFeng** [comment]
Ok I see. 
Do we settle for a `get_` method for runes, items and summoner spells then ? 

`champion.get_item("Luden's Echo").damage`
`champion.get_rune("Electrocute").damage`
`champion.get_summoner_spell("Ignite").damage`

**Comment by Lysxia** [comment]
That looks good to me.
